### PR TITLE
event_sync: add support for breakout rooms

### PR DESCRIPTION
**Pull request by shawnchin**
Fixes https://github.com/jitsi-contrib/prosody-plugins/issues/14

@damencho May I trouble you for a review when you have a moment to spare? Thanks :)

### CODE REVIEW

**Comment by damencho** [comment]
👍

**Comment by damencho** [comment]
Can you please update Readme, dropping the she that is around the occupant.

**Review by damencho — APPROVED** [review]

**Comment by damencho** [comment]
Thanks 👍

**Comment by damencho** [comment]
:)

**Comment by shawnchin** [comment]
Thanks for reviewing 🙇

**Pull request merged**
